### PR TITLE
Rename installed files to r2cutter

### PR DESCRIPTION
**Pull request by thestr4ng3r**
This changes the installed executable and metadata files to be called "r2cutter" to conform with the project name. This makes it possible to have both Cutter and r2cutter installed side by side and it helps distribution maintainers to avoid clashes if they want to package both.

I hope I didn't miss anything, but I tested it with all three included build systems and checked the exact files that were installed and they all looked sane, so should be ok.

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Looks like Github's ubuntu image has some issues, but that is unrelated:
```
Err:20 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 mesa-common-dev amd64 20.0.8-0ubuntu1~20.04.1
  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libglx-dev_1.3.1-1ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
Fetched 3537 kB in 0s (13.0 MB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libgl-dev_1.3.1-1ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/mesa-common-dev_20.0.8-0ubuntu1~20.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Review by karliss — CHANGES_REQUESTED** [review]
Executable and icon name in .desktop file need to be updated, probably also in appdata.xml

**Comment by thestr4ng3r** [comment]
Ok I see. One of the problems that this is trying to fix is that some distributions have packages called `radare2-cutter` that will not transition to rizin because their meaning is "Cutter for radare2". But if they still want to package Cutter, this package would have file conflicts with that. If r2cutter would rename the files upstream, even without a release, it would make sense for them to also adopt these changes in the packages and thus resolve the conflicts.
But I also understand not wanting to rename everything to a possibly provisional-only name.

**Comment by trufae** [comment]
Ok, @thestr4ng3r thanks for the PR!

I think it's fine to do this renaming for now, and new builds may be published to avoid the naming confussion. Let's use r2cutter.

**Comment by trufae** [comment]
Please rebase this PR i have updated the r2cutter svg files, do you know how were the icons generated?

**Comment by thestr4ng3r** [comment]
Rebased.
I made the icon in Inkscape and as far as I can tell the `src/img/cutter.svg`/`src/img/r2cutter.svg` is the original, raw file that all others were derived from, through applying some boolean ops to the paths, scaling or re-coloring.
The way the svgs were changed in c25f2264b7bd505f236b9cfc33cbf2742c022b06 looks correct to me.

**Comment by trufae** [comment]
About the icons i mean the .icns and .ico files. I updated all the svg files already, but needs to rename the files (didnt moved because you were into that refactoring already).

The red CIs seems to be red for unrelated reasons. Do you think the pr is ready to merge now? the CI can be fixed later I guess.

**Comment by thestr4ng3r** [comment]
I don't know about the .ico but tracking back the .icns from 9f582b3b822b456a308afe8e058b2fe71562d2f2 through 5aedbdba7130ff31295b8566f01998d7b00d60d7, it was created from the current `cutter.svg`/`r2cutter.svg`. This is the docs for creating an icns: https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html
I think the most convenient way will be to write a small shell script that makes this `<name>.iconset` folder with `icon_16x16.png` up to `icon_512x512@2x.png` by converting the svg to the respective resolutions using imagemagick and then running `iconutil -c icns <name>.iconset`. Iirc that is also how I did it back then but I can't find any local script for it anymore.

Yes, I think the pr should be ready to merge. In fact, it already fixes some of the CI because on master the change in `src/resources.qrc` breaks the build.

**Comment by trufae** [comment]
I know the steps to create the macOS icons. but i though there was a documented way to generate them or a script. 

Thanks for the PR! merging now! ill look into the iconset later when i have some spare time

**Comment by thestr4ng3r** [comment]
Thanks!

**Pull request merged**
